import numpy as np

Creating NumPy Arrays form a python list

In [2]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Built-in Methods

arrange

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

Zeros and ones

In [11]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [12]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [13]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

# linspace

In [3]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [4]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

# eye:


creates an identity matrix

In [5]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

# Random

Numpy also has lot of ways to create random number arrays:

In [6]:
np.random.rand(2)

array([ 0.44269963,  0.17425475])

In [7]:
np.random.rand(5,5)

array([[ 0.22294053,  0.26332541,  0.01715219,  0.98687788,  0.58853452],
       [ 0.53951746,  0.70039194,  0.51403353,  0.66087699,  0.22439203],
       [ 0.50607522,  0.89974289,  0.25958521,  0.72684569,  0.97593714],
       [ 0.86774726,  0.0819469 ,  0.49783737,  0.38012703,  0.76375434],
       [ 0.96283598,  0.19281555,  0.91338485,  0.15677709,  0.79650958]])

# randn 

retun a sampe (or samples) from the "standard normal" distribution. Unlike rand which is uniform

In [10]:
np.random.randn(2)

array([ 0.64422588,  0.83648211])

In [11]:
np.random.randn(5,5)

array([[ 0.86951051, -0.03236177, -1.25449721,  0.37628252,  1.11059165],
       [-1.59666399,  1.86356113, -0.24835456, -0.47912247, -0.39092998],
       [ 0.3756832 , -0.39752964, -1.91822644, -0.2048592 ,  0.71372665],
       [-1.13817563, -1.13267495,  1.02512535, -1.22411648, -0.73925539],
       [ 1.3162521 ,  0.77673274, -0.63972471, -1.80753865,  0.72514531]])

# randint

 Return random integers from low (inclusive) to high(exclusive)

In [12]:
np.random.randint(1,100)

62

In [13]:
np.random.randint(1,100,10)

array([55, 35, 41, 71, 34,  7,  4, 51,  1, 48])

# Array Attributes and Methods

In [29]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
ranarr

array([27, 48, 13,  9, 10,  4,  1, 24, 10, 33])

# Reshape

Returns an array containing the same data with a new shape

In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# max, min, argmax, argmin

In [23]:
ranarr

array([27, 48, 13,  9, 10,  4,  1, 24, 10, 33])

In [24]:
ranarr.max()

48

In [25]:
ranarr.argmax()

1

In [26]:
ranarr.min()

1

In [27]:
ranarr.argmin()

6

# Shape

Shape is an attribute that arrays have(not a method):

In [31]:
# Vector
arr.shape

(25,)

In [32]:
# Notice the two sets of brackets
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [33]:
arr.reshape(1,25).shape

(1, 25)

In [34]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [35]:
arr.reshape(25,1).shape

(25, 1)

# dtype 

is used to grab the data type of the object in the array

In [36]:
arr.dtype

dtype('int32')